spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(x6nBVqwNtC3FPXPUIzy3W0rqsCXP0UPDXT69VCX6M6tyjbrgoTkAj15L9v+k2uyzUa/gGYYfnbv1fzwhI+e1XMnk4NCH+m3Vs46XsY2hX1eEgvlUrICvGg==)
    username: ENC(uL7k1DzNozYov07EeJa/2g==)
    password: ENC(zYa4HBAWShBPBoxDA0FzXewAPXLtIXwA)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

# logging
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
  config: classpath:logback-spring.xml

# encryption
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator